const products = [
  {
    id: 1,
    name: "Wireless Headphones",
    price: 2499,
    category: "Electronics",
    rating: 4.5,
    stock: true,
    description: "High quality wireless headphones with noise cancellation.",
  },
  {
    id: 2,
    name: "Bluetooth Speaker",
    price: 1799,
    category: "Electronics",
    rating: 4.0,
    stock: true,
    description: "Portable Bluetooth speaker with deep bass.",
  },
  {
    id: 3,
    name: "Smart Watch",
    price: 3599,
    category: "Wearables",
    rating: 4.2,
    stock: false,
    description: "Smart watch with heart rate monitor and GPS.",
  },
  {
    id: 4,
    name: "USB Type-C Cable",
    price: 199,
    category: "Accessories",
    rating: 4.7,
    stock: true,
    description: "Durable and fast charging USB-C cable.",
  },
  {
    id: 5,
    name: "Power Bank 10000mAh",
    price: 1299,
    category: "Accessories",
    rating: 4.1,
    stock: true,
    description: "Compact power bank with fast charging support.",
  },
  {
    id: 6,
    name: "Laptop Stand",
    price: 999,
    category: "Accessories",
    rating: 4.0,
    stock: true,
    description: "Ergonomic laptop stand for better posture.",
  },
  {
    id: 7,
    name: "Ergonomic Mouse",
    price: 799,
    category: "Electronics",
    rating: 4.3,
    stock: true,
    description: "Comfortable ergonomic mouse with wireless connectivity.",
  },
  {
    id: 8,
    name: "Mechanical Keyboard",
    price: 2299,
    category: "Electronics",
    rating: 4.6,
    stock: false,
    description: "Mechanical keyboard with RGB lighting.",
  },
  {
    id: 9,
    name: "Webcam HD",
    price: 1499,
    category: "Electronics",
    rating: 3.9,
    stock: true,
    description: "HD webcam perfect for video calls.",
  },
  {
    id: 10,
    name: "External Hard Drive 1TB",
    price: 3799,
    category: "Storage",
    rating: 4.4,
    stock: true,
    description: "Reliable external hard drive with 1TB capacity.",
  },

  {
    id: 11,
    name: "Pen Drive 64GB",
    price: 699,
    category: "Storage",
    rating: 4.2,
    stock: true,
    description: "High-speed pen drive with 64GB storage.",
  },
  {
    id: 12,
    name: "LED Monitor 24 inch",
    price: 8499,
    category: "Electronics",
    rating: 4.3,
    stock: false,
    description: "24-inch LED monitor with vibrant colors.",
  },
  {
    id: 13,
    name: "Smartphone Holder",
    price: 299,
    category: "Accessories",
    rating: 3.8,
    stock: true,
    description: "Adjustable smartphone holder for desks.",
  },
  {
    id: 14,
    name: "Tripod Stand",
    price: 549,
    category: "Accessories",
    rating: 4.0,
    stock: true,
    description: "Lightweight tripod stand for cameras and phones.",
  },
  {
    id: 15,
    name: "DSLR Camera",
    price: 48999,
    category: "Electronics",
    rating: 4.7,
    stock: false,
    description: "Professional DSLR camera with multiple lenses.",
  },
  {
    id: 16,
    name: "Gaming Chair",
    price: 9999,
    category: "Furniture",
    rating: 4.4,
    stock: true,
    description: "Comfortable gaming chair with adjustable height.",
  },
  {
    id: 17,
    name: "Wireless Charger",
    price: 1099,
    category: "Accessories",
    rating: 4.1,
    stock: true,
    description: "Fast wireless charger compatible with many phones.",
  },
  {
    id: 18,
    name: "Tablet 10 inch",
    price: 13499,
    category: "Electronics",
    rating: 4.3,
    stock: true,
    description: "10 inch tablet with high-resolution display.",
  },
  {
    id: 19,
    name: "Bluetooth Earbuds",
    price: 1899,
    category: "Wearables",
    rating: 4.0,
    stock: false,
    description: "Wireless earbuds with clear sound quality.",
  },
  {
    id: 20,
    name: "WiFi Router Dual Band",
    price: 2099,
    category: "Networking",
    rating: 4.2,
    stock: true,
    description: "Dual band WiFi router with strong signal.",
  },

  {
    id: 21,
    name: "Smart Light Bulb",
    price: 799,
    category: "Home Automation",
    rating: 4.5,
    stock: true,
    description: "Smart bulb with color changing options.",
  },
  {
    id: 22,
    name: "Electric Kettle",
    price: 1399,
    category: "Home Appliances",
    rating: 4.1,
    stock: true,
    description: "1.5L electric kettle with auto shutoff.",
  },
  {
    id: 23,
    name: "Air Purifier",
    price: 5499,
    category: "Home Appliances",
    rating: 4.3,
    stock: false,
    description: "Compact air purifier with HEPA filter.",
  },
  {
    id: 24,
    name: "Robot Vacuum",
    price: 12999,
    category: "Home Appliances",
    rating: 4.0,
    stock: true,
    description: "Smart robot vacuum cleaner with scheduling.",
  },
  {
    id: 25,
    name: "Fitness Tracker",
    price: 2999,
    category: "Wearables",
    rating: 4.2,
    stock: true,
    description: "Fitness tracker with heart rate and sleep monitor.",
  },
  {
    id: 26,
    name: "Gaming Mouse",
    price: 1599,
    category: "Electronics",
    rating: 4.4,
    stock: true,
    description: "High precision gaming mouse with programmable buttons.",
  },
  {
    id: 27,
    name: "Laptop Backpack",
    price: 2499,
    category: "Accessories",
    rating: 4.1,
    stock: true,
    description: "Durable backpack with laptop compartment.",
  },
  {
    id: 28,
    name: "Noise Cancelling Earphones",
    price: 2999,
    category: "Wearables",
    rating: 4.3,
    stock: false,
    description: "Earphones with active noise cancellation.",
  },
  {
    id: 29,
    name: "Smart Thermostat",
    price: 4999,
    category: "Home Automation",
    rating: 4.0,
    stock: true,
    description: "Smart thermostat with app control.",
  },
  {
    id: 30,
    name: "Electric Toothbrush",
    price: 2199,
    category: "Personal Care",
    rating: 4.2,
    stock: true,
    description: "Electric toothbrush with multiple modes.",
  },

  {
    id: 31,
    name: "Hair Dryer",
    price: 1799,
    category: "Personal Care",
    rating: 4.1,
    stock: true,
    description: "Compact hair dryer with heat settings.",
  },
  {
    id: 32,
    name: "4K Smart TV 43 inch",
    price: 35999,
    category: "Electronics",
    rating: 4.5,
    stock: true,
    description: "43 inch 4K UHD smart TV with HDR.",
  },
  {
    id: 33,
    name: "Portable Projector",
    price: 14999,
    category: "Electronics",
    rating: 4.0,
    stock: false,
    description: "Compact portable projector for movies.",
  },
  {
    id: 34,
    name: "Smart Door Lock",
    price: 7999,
    category: "Home Automation",
    rating: 4.2,
    stock: true,
    description: "Keyless smart door lock with app control.",
  },
  {
    id: 35,
    name: "Gaming Console",
    price: 29999,
    category: "Electronics",
    rating: 4.6,
    stock: true,
    description: "Latest generation gaming console.",
  },
  {
    id: 36,
    name: "Electric Scooter",
    price: 25999,
    category: "Vehicles",
    rating: 4.1,
    stock: true,
    description: "Electric scooter with 20 km range.",
  },
  {
    id: 37,
    name: "Smartphone 128GB",
    price: 19999,
    category: "Electronics",
    rating: 4.3,
    stock: true,
    description: "Smartphone with high performance and camera.",
  },
  {
    id: 38,
    name: "VR Headset",
    price: 18999,
    category: "Electronics",
    rating: 4.0,
    stock: false,
    description: "Virtual reality headset for immersive experience.",
  },
  {
    id: 39,
    name: "Electric Grill",
    price: 4999,
    category: "Home Appliances",
    rating: 4.1,
    stock: true,
    description: "Compact electric grill for indoor cooking.",
  },
  {
    id: 40,
    name: "Smart Alarm Clock",
    price: 1299,
    category: "Home Automation",
    rating: 4.0,
    stock: true,
    description: "Smart alarm clock with multiple functions.",
  },

  {
    id: 41,
    name: "Wireless Gaming Headset",
    price: 3499,
    category: "Electronics",
    rating: 4.4,
    stock: true,
    description: "Wireless headset optimized for gaming.",
  },
  {
    id: 42,
    name: "Smart Glasses",
    price: 10999,
    category: "Wearables",
    rating: 3.9,
    stock: false,
    description: "Smart glasses with augmented reality features.",
  },
  {
    id: 43,
    name: "Electric Kettle 2L",
    price: 1799,
    category: "Home Appliances",
    rating: 4.2,
    stock: true,
    description: "2-liter electric kettle with safety features.",
  },
  {
    id: 44,
    name: "Fitness Smart Scale",
    price: 2299,
    category: "Wearables",
    rating: 4.1,
    stock: true,
    description: "Smart scale with BMI and body fat analysis.",
  },
  {
    id: 45,
    name: "USB Hub 4 Ports",
    price: 499,
    category: "Accessories",
    rating: 4.0,
    stock: true,
    description: "USB hub with 4 high-speed ports.",
  },
];

export default products;
